import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Prisma output — regenerated by `prisma generate`, never hand-edited.
    "src/generated/**",
  ]),
  {
    // CLAUDE.md requires every farming query to be scoped by season. That is
    // only enforceable if queries live in one place, so the client is reachable
    // from src/server/** alone — everything else goes through a query module.
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/server/**", "src/lib/prisma.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@/lib/prisma",
              message:
                "Import a query from @/server/queries instead. Direct Prisma access outside src/server bypasses the season scoping rule in CLAUDE.md.",
            },
          ],
          patterns: [
            {
              group: ["@/generated/prisma", "@/generated/prisma/*"],
              message:
                "Use the types re-exported by @/server/queries rather than reaching into the generated client.",
            },
          ],
        },
      ],
    },
  },
]);

export default eslintConfig;
