// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // tsx, not plain node: the generated client uses extensionless imports
    // that Node's ESM resolver rejects.
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // CLI-only (migrate, studio, db execute). Uses the session-mode pooler,
    // which supports DDL; the app itself connects via DATABASE_URL in
    // src/lib/prisma.ts. Falls back to DATABASE_URL for setups with no pooler.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
